package tests.testservicesnode;

import org.openide.util.NbPreferences;

/**
 *
 * @author jor
 */
public class LoginForm extends javax.swing.JPanel {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        setInitialValues();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        userName = new javax.swing.JTextField();
        userPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        urlPrefix = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(LoginForm.class, "LoginForm.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(LoginForm.class, "LoginForm.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(LoginForm.class, "LoginForm.jLabel3.text")); // NOI18N

        name.setText(org.openide.util.NbBundle.getMessage(LoginForm.class, "LoginForm.name.text")); // NOI18N
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLostHandler(evt);
            }
        });

        userName.setText(org.openide.util.NbBundle.getMessage(LoginForm.class, "LoginForm.userName.text")); // NOI18N
        userName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                userNameFocusLost(evt);
            }
        });

        userPassword.setText(org.openide.util.NbBundle.getMessage(LoginForm.class, "LoginForm.userPassword.text")); // NOI18N
        userPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                userPasswordFocusLost(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(LoginForm.class, "LoginForm.jLabel4.text")); // NOI18N

        urlPrefix.setText(org.openide.util.NbBundle.getMessage(LoginForm.class, "LoginForm.urlPrefix.text")); // NOI18N
        urlPrefix.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                urlPrefixFocusLost(evt);
            }
        });
        urlPrefix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlPrefixActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addComponent(userName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(urlPrefix, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(urlPrefix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void urlPrefixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlPrefixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urlPrefixActionPerformed

    private void nameFocusLostHandler(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLostHandler
        if(name.getText()!=null && !name.getText().isEmpty()) {
            NbPreferences.forModule(LoginForm.class).put("name", name.getText());
        }
    }//GEN-LAST:event_nameFocusLostHandler

    private void urlPrefixFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_urlPrefixFocusLost
        if(urlPrefix.getText()!=null && !urlPrefix.getText().isEmpty()) {
            NbPreferences.forModule(LoginForm.class).put("urlPrefix", urlPrefix.getText());
        }
    }//GEN-LAST:event_urlPrefixFocusLost

    private void userNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFocusLost
        if(userName.getText()!=null && !userName.getText().isEmpty()) {
            NbPreferences.forModule(LoginForm.class).put("userName", userName.getText());
        }
    }//GEN-LAST:event_userNameFocusLost

    private void userPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userPasswordFocusLost
        if(userPassword.getText()!=null && !userPassword.getText().isEmpty()) {
            NbPreferences.forModule(LoginForm.class).put("userPassword", userPassword.getText());
        }
    }//GEN-LAST:event_userPasswordFocusLost

    public String getName() {
        return name.getText();
    }

    public String getUrlPrefix() {
        return urlPrefix.getText();
    }

    public String getUserName() {
        return userName.getText();
    }

    public String getUserPassword() {
        return userPassword.getText();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField name;
    private javax.swing.JTextField urlPrefix;
    private javax.swing.JTextField userName;
    private javax.swing.JTextField userPassword;
    // End of variables declaration//GEN-END:variables

    private void setInitialValues() {
        String _name;
        if( (_name = NbPreferences.forModule(LoginForm.class).get("name", "-- OpenStack name --")) != null) {
           name.setText(_name);
        }
        
        String _urlPrefix;
        if( (_urlPrefix = NbPreferences.forModule(LoginForm.class).get("urlPrefix", "-- Keystone url --")) != null) {
           urlPrefix.setText(_urlPrefix);
        }
        
        String _userName;
        if( (_userName = NbPreferences.forModule(LoginForm.class).get("userName", "-- username --")) != null) {
           userName.setText(_userName);
        }
        
        String _userPassword;
        if( (_userPassword = NbPreferences.forModule(LoginForm.class).get("userPassword", "-- password --")) != null) {
           userPassword.setText(_userPassword);
        }

    }
}
